import { AtemAny } from './Atem'
import { CasparCGAny } from './CasparCG'
import { OBSAny } from './OBS'
import { VMixAny } from './VMix'

export type ResourceAny = CasparCGAny | AtemAny | OBSAny | VMixAny

export interface ResourceBase {
	resourceType: ResourceType

	deviceId: string
	id: string // Must be globally unique
}
export enum ResourceType {
	CASPARCG_SERVER = 'CASPARCG_SERVER',

	CASPARCG_MEDIA = 'CASPARCG_MEDIA',
	CASPARCG_TEMPLATE = 'CASPARCG_TEMPLATE',

	ATEM_ME = 'ATEM_ME',
	ATEM_DSK = 'ATEM_DSK',
	ATEM_AUX = 'ATEM_AUX',
	ATEM_SSRC = 'ATEM_SSRC',
	ATEM_SSRC_PROPS = 'ATEM_SSRC_PROPS',
	ATEM_MACRO_PLAYER = 'ATEM_MACRO_PLAYER',
	ATEM_AUDIO_CHANNEL = 'ATEM_AUDIO_CHANNEL',
	ATEM_MEDIA_PLAYER = 'ATEM_MEDIA_PLAYER',

	OBS_SCENE = 'OBS_SCENE',
	OBS_TRANSITION = 'OBS_TRANSITION',
	OBS_RECORDING = 'OBS_RECORDING',
	OBS_STREAMING = 'OBS_STREAMING',
	OBS_SOURCE_SETTINGS = 'OBS_SOURCE_SETTINGS',
	OBS_MUTE = 'OBS_MUTE',
	OBS_RENDER = 'OBS_RENDER',

	VMIX_INPUT = 'VMIX_INPUT',
	VMIX_INPUT_SETTINGS = 'VMIX_INPUT_SETTINGS',
	VMIX_AUDIO_SETTINGS = 'VMIX_AUDIO_SETTINGS',
	VMIX_OUTPUT_SETTINGS = 'VMIX_OUTPUT_SETTINGS',
	VMIX_OVERLAY_SETTINGS = 'VMIX_OVERLAY_SETTINGS',
	VMIX_RECORDING = 'VMIX_RECORDING',
	VMIX_STREAMING = 'VMIX_STREAMING',
	VMIX_EXTERNAL = 'VMIX_EXTERNAL',
	VMIX_FADE_TO_BLACK = 'VMIX_FADE_TO_BLACK',
	VMIX_FADER = 'VMIX_FADER',
}
